POST http://localhost:5500/videos
Content-Type: application/json

{
    "title": "Video Node",
    "description": "This is the first video",
    "duration": 180
}

###

GET http://localhost:5500/videos?search=Node

###

PUT http://localhost:5500/videos/09a4c165-93d5-4c62-a1d8-aab05426e280
Content-Type: application/json

{   
    "title": "Video 3",
    "description": "This is the new description of the second video",
    "duration": 180
}

### 
DELETE http://localhost:5500/videos/77f593d7-3230-43a1-a78d-45e5ae020575